### ISSUE TITLE
Save events as *.jfr file

### ISSUE THREAD

**Issue by tmodelsk** [moditect/jfrunit#101]
It would be useful to save captured events as *.jfr file on disk.

Something like: 

> // ...
> jfrEvents.awaitEvents();
> // ...
> jfrEvents.saveAsJfrFile(Path.of("/here/profiling.jfr"))

**Comment by gunnarmorling** [comment]
This should be the case already. Have you looked at target/jfrunit, there
should be a file for each test method.

>

**Comment by tmodelsk** [comment]
Indeed, *.jfr files are there, thanks. 
And thanks for great tool! 
My performance @JfrEventTest tests are seamlessly working with @SpringBootTest - great!

**Comment by gunnarmorling** [comment]
Excellent, happy to hear that. Thanks for the nice feedback!

>
