### ISSUE TITLE
Odd name generated for OBJECT_ALLOCATION_IN_NEW_TL_AB

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/jfrunit#115]
The generated name should be `OBJECT_ALLOCATION_IN_NEW_TLAB` instead of `OBJECT_ALLOCATION_IN_NEW_TL_AB`.

I suppose it's due to multiple consecutive upper-case characters in the original event type name, `jdk.ObjectAllocationInNewTLAB`.

// CC @Croway

**Comment by Croway** [comment]
Hi @gunnarmorling , I spent some time with regexp but I only managed to get an headache, the PR solution works in every case.

**Comment by gunnarmorling** [comment]
Done via #116.
