### ISSUE TITLE
Support for Spock

### ISSUE THREAD

**Issue by phejl** [moditect/jfrunit#37]
It would be great to have a support for [Spock](https://spockframework.org). So one could use the library like this:

```groovy
import dev.morling.jfrunit.*
import spock.lang.Specification

import java.time.Duration

import static dev.morling.jfrunit.JfrEventsAssert.*
import static dev.morling.jfrunit.ExpectedEvent.*

@JfrEventTest
class JfrSpec extends Specification {

    JfrEvents jfrEvents = new JfrEvents()

    @EnableEvent('jdk.GarbageCollection')
    @EnableEvent('jdk.ThreadSleep')
    def 'should Have GC And Sleep Events'() throws Exception {
        when:
        System.gc()
        sleep(1000)

        then:
        assertThat(jfrEvents).contains(event('jdk.GarbageCollection'))
        assertThat(jfrEvents).contains(
                event('jdk.ThreadSleep').with('time', Duration.ofSeconds(1)))
    }
}
```

**Comment by aalmiray** [comment]
AFAICT Spock 2.0 supports Junit Platform's Vintage and Jupiter engines which would allow Junit5 extension to be seamlessly consumed. Adding @leonard84

**Comment by gunnarmorling** [comment]
Interesting idea, I certainly could see us doing that. What's the language used above, Groovy?

**Comment by aalmiray** [comment]
That is indeed Groovy.

**Comment by leonard84** [comment]
Spock 2.0 doesn't support junit-jupiter extensions (the jupiter API is far to complex for an easy support), although there is still best-effort support for junit4 rules.

The best thing would be to write a native Spock extension.

**Comment by gunnarmorling** [comment]
> That is indeed Groovy.

I see. So I like that apparently this would provide a way to avoid the
need for the explicit awaitEvents() call between the given/when and
then. We might wrap those blocks in Lambda expressions for a Java API
of course, alternatively.

**Comment by leonard84** [comment]
>  I like that apparently this would provide a way to avoid the need for the explicit awaitEvents() call between the given/when and then.

This might not be possible to achieve via extensions at the moment, as spock doesn't expose those blocks at runtime to extensions. There is an open issue https://github.com/spockframework/spock/issues/538 that touches on this.

**Comment by phejl** [comment]
I think I might have a PR :)

**Comment by phejl** [comment]
https://github.com/moditect/jfrunit/pull/38

**Comment by phejl** [comment]
@gunnarmorling I guess this can be closed now.

**Comment by gunnarmorling** [comment]
Indeed, thx!
