### ISSUE TITLE
Issue building with JDK 16

### ISSUE THREAD

**Issue by Thihup** [moditect/jfrunit#39]
When using JDK 16 to build this project it fails with the following error:
```
[ERROR] /jfrunit/src/test/java/dev/morling/jfrunit/StackTraceDisabledSampleEvent.java:[26,8] cannot access jdk.internal.event.Event
  class file for jdk.internal.event.Event not found
[INFO] 1 error
```
I'll try to get more information about it

**Comment by gunnarmorling** [comment]
Yes, I believe this is due to using --release=15. I'm not quite sure how it
can be done in a more version agnostic way.

>

**Comment by aalmiray** [comment]
Perhaps configuring Maven toolchains along with a profile?

**Comment by gunnarmorling** [comment]
I've created https://github.com/moditect/jfrunit/pull/68 for moving to JDK 16 as a baseline. Supporting 14 or 15 doesn't make any sense at this point, given they are EOL by now. Adding support for the previous LTS (11) is tracked via #5.
