### ISSUE TITLE
Allow for more idiomatic Groovy checks in Spock

### ISSUE THREAD

**Issue by phejl** [moditect/jfrunit#74]
The current Spock integration does not promote and easen post condition checks. We should remove AssertJ style of checks in Spock tests/docs and make it easy and better fit in Groovy ecosystem.

**Comment by gunnarmorling** [comment]
@phejl, I think we can close this one, right?

**Comment by phejl** [comment]
> @phejl, I think we can close this one, right?

Yes. Sure.

**Comment by gunnarmorling** [comment]
Thx again, @phejl!
