### ISSUE TITLE
Release fails with JDK 16

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/jfrunit#78]
See https://github.com/moditect/jfrunit/runs/3232400668?check_suite_focus=true:

```
Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @1fdca564
```

Heeelp, @aalmiray ;)

**Comment by gunnarmorling** [comment]
I guess we could pass `--illegal-access=permit` as a work-around for now.

**Comment by gunnarmorling** [comment]
@aalmiray, so assuming I can patch fix this via `MAVEN_OPTS`, how do I re-do a release for the same tag as before?

**Comment by aalmiray** [comment]
Delete the tag. Undo the version commit (use the force, Gunnar!) and trigger once again.

**Comment by gunnarmorling** [comment]
Ok, will do. I'll be now offline for an hour or so; just in case you wanted to give it a try yourself, feel free to do so (but no worries if not, I'll do so otherwise later tonight).

**Comment by gunnarmorling** [comment]
Deleted latest HEAD commit and the tag.

**Comment by gunnarmorling** [comment]
Logged https://issues.sonatype.org/browse/NEXUS-28575 for getting this fixed upstream. For Java 16, we're good with the workaround, but for Java 17, we'll need a new version of the staging plug-in with this fix in place.
