### ISSUE TITLE
Meaningful jfr dump file names

### ISSUE THREAD

**Issue by phejl** [moditect/jfrunit#82]
The name of the jfr dump files are created from the class name and method. This is not really useful for Spock tests.

**Comment by gunnarmorling** [comment]
Thx, that makes sense. Took a quick look at the commit referenced above, LGTM, too.

**Comment by phejl** [comment]
Thanks @gunnarmorling. I'll file a PR once I'm back from vacation. Sadly or luckily I don't have much time to code at the moment :)

**Comment by gunnarmorling** [comment]
Sounds good. Have a great time off 🏖️  :)

**Comment by phejl** [comment]
Ok, I believe PR is ready now.

**Comment by gunnarmorling** [comment]
Welcome back :) PR merged, thanks a lot!
